
const countriesData = [
// Middle East
{ code: 'BH', name: 'Bahrain' },
{ code: 'EG', name: 'Egypt' },
{ code: 'IR', name: 'Iran' },
{ code: 'IQ', name: 'Iraq' },
{ code: 'JO', name: 'Jordan' },
{ code: 'KW', name: 'Kuwait' },
{ code: 'LB', name: 'Lebanon' },
{ code: 'OM', name: 'Oman' },
{ code: 'QA', name: 'Qatar' },
{ code: 'SA', name: 'Saudi Arabia' },
{ code: 'SY', name: 'Syria' },
{ code: 'AE', name: 'UAE' },
{ code: 'YE', name: 'Yemen' },
{ code: 'DZ', name: 'Algeria' },
{ code: 'AO', name: 'Angola' },
{ code: 'KE', name: 'Kenya' },
{ code: 'GH', name: 'Ghana' },
{ code: 'MA', name: 'Morocco' },
{ code: 'NG', name: 'Nigeria' },
{ code: 'ZA', name: 'South Africa' },
{ code: 'UG', name: 'Uganda' },
{ code: 'TZ', name: 'Tanzania' },
{ code: 'ZM', name: 'Zambia' },
{ code: 'ET', name: 'Ethiopia' },
{ code: 'SD', name: 'Sudan' },
{ code: 'IN', name: 'India' },
{ code: 'PK', name: 'Pakistan' },
{ code: 'CN', name: 'China' },
{ code: 'JP', name: 'Japan' },
{ code: 'KR', name: 'South Korea' },
{ code: 'BD', name: 'Bangladesh' },
{ code: 'LK', name: 'Sri Lanka' },
{ code: 'NP', name: 'Nepal' },
{ code: 'BT', name: 'Bhutan' },
{ code: 'MV', name: 'Maldives' },
{ code: 'TH', name: 'Thailand' },
{ code: 'VN', name: 'Vietnam' },
{ code: 'MY', name: 'Malaysia' },
{ code: 'ID', name: 'Indonesia' },
{ code: 'PH', name: 'Philippines' },
{ code: 'MM', name: 'Myanmar' },
{ code: 'KH', name: 'Cambodia' },
{ code: 'LA', name: 'Laos' },
{ code: 'SG', name: 'Singapore' },
{ code: 'BN', name: 'Brunei' },
{ code: 'TL', name: 'Timor-Leste' },
];